### ISSUE TITLE
Build fails: module 'dace.transformation.passes.scalar_to_symbol' has no attribute 'promote_scalars_to_symbols'

### ISSUE THREAD

**Issue by jamesavery** [spcl/c2dace#5]
calling make on a fresh clone breaks in the following way: 
...
mallocing  alpha  of size  [1]  and type  double
FUNC:  ddot
ENDF:  ddot
FUNC:  waxpby
ENDF:  waxpby
FUNC:  waxpby
ENDF:  waxpby
ENDF:  HPCCG
ENDF:  main
SDFG creation done
Traceback (most recent call last):
  File "c2dace/c2d.py", line 93, in <module>
    c2d_workflow(_dir, filecore, fileextension, autoopt=False, verbose=True, print_ast=True)
  File "/store/work/CheetahAI/c2dace/c2dace/c2d_workflow.py", line 237, in c2d_workflow
    promoted = scal2sym.promote_scalars_to_symbols(sd)
AttributeError: module 'dace.transformation.passes.scalar_to_symbol' has no attribute 'promote_scalars_to_symbols'

**Comment by leporia** [comment]
They changed how transformations are called from DaCe. PR #7 should fix this
